---
title: "CodeBook.md"
author: "Soumya R Das"
date: "May 1, 2016"
output: md_document
---

## Getting and Cleaning Data Course Project

### Requirements for the Project:
> Analyze the data collected in the project named - Human Activity Recognition Using Smartphones Dataset. Create one R script named run_analysis.R that does the following:
>
  * The submitted data set is tidy.
  * Merges the training and the test sets to create one data set.
  * Extracts only the measurements on the mean and standard deviation for each     measurement.
  * Uses descriptive activity names to name the activities in the data set
  * Appropriately labels the data set with descriptive variable names.
  * From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
  
### Additional submission requirements for the Project are: 
> 
  * The submitted data set is tidy.
  * The Github repo contains the required scripts.
  * GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
  * The README that explains the analysis files is clear and understandable.
  * The work submitted for this project is the work of the student who submitted it.
  
### Data for the project

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. 

Full data for the analysis can be downloaded from the below link
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

### Data Overview
The dataset includes the following files:

* 'README.txt'
* 'features_info.txt': Shows information about the variables used on the feature vector.
* 'features.txt': List of all features.
* 'activity_labels.txt': Links the class labels with their activity name.
* 'train/X_train.txt': Training set.
* 'train/y_train.txt': Training labels.
* 'test/X_test.txt': Test set.
* 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

* 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 
* 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 
* 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 
* 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 


### Overall Process:  
The below process was followed to arrive at the two tidy data sets required for the project.

1. The text files are to be comsumed and filled into data tables for the analysis.
2. The activity_labels.txt file contains the different activities that can be performed
3. The features.txt file contains the different measurements that can be takes
4. The test/X_test.txt and test/X_train.txt files contain 561 different type of measurements(variables) for about 30 subjects. There can be multiple rows for each subject in each file. The number of rows in each file are also different.
4. Data from the two files are merged into a single data table(using rbind()). Similaryly, data from  y_test.txt and y_train.txt are merged and subject_test.txt and subject_train.txt are merged.
5. Column/Variable names in the resultant data sets are then changed to make them more readable and meaningful (instead of names like V1, V2, etc)
6. As the requirement clearly mentions that we only need to analyze measurements corresponding to mean and standard deviation, only the columns containing "mean" and "std" are taken into consideration
7. The data sets obtained in step 4 are then merged using cbind() to give the final data set. 
8. The final data set obtained in Step 7 is then grouped by Activity and Subject columns and summarised using the mean function. 
9. Both the data sets produced by the Step 7 and Step 8 are then written to file using the row.names = FALSE clause.

Please refer to the README.md file for detailed explanation of how the result has been arrived at.

